SYNTHESIZED_DIR := $(abspath $(dir $(lastword $(MAKEFILE_LIST)))/../)
EXTRA-SRCS-y := $(shell echo $(SYNTHESIZED_DIR)/../libvig/unverified/*.c)
LDLIBS := -lpcap
SYNTHESIZED_FILE := $(SYNTHESIZED_DIR)/build/synthesized/nf.c
